version: '2'
services:
  jhipsterapp-app:
    image: jhipsterapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapp-mysql:3306/jhipsterapp?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterapp-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsterapp-mysql:
    extends:
      file: mysql.yml
      service: jhipsterapp-mysql
  jhipsterapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterapp-elasticsearch
